name: Main
on:
  push: 
    branches: 
        - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          filename: "/report.json"
          folderId: ${{ secrets.folderId }}
          name: "documentation.json" # optional string
          overwrite: "true" # optional boolean