name: Main
on:
  push: 
    branches: 
        - main

jobs:
  gdrive-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Archive files
        run: |
          sudo apt-get update
          sudo apt-get install zip
          zip -r archive.zip *

      - name: Upload to gdrive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: report.zip
          name: documentation.zip
          folderId: ${{ secrets.FOLDERID }}
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          encoded: false